name: tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./server
        run: npm ci
      - name: Run tests
        working-directory: ./server
        run: npm run test
