name: tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory into server
        run: cd server
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run testg
